name: build_test

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  build_test_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Show framework path
        run: |
          echo "Framework path: ${{ inputs.path }}"
      - name: Compile Framework repo
        run: |
          cd ${{ inputs.path }}
          mkdir build
          cd build
          cmake ..; make -j 4;
          echo "Done compile"
