name: Subtree Push

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  subtree-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Repository
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0
    - name: Git Config
      run: |
        #git config --global user.email "test@test.com"
        #git config --global user.name "test_bot"
        git config --global url.https://api:${{ secrets.ACTION_TOKEN }}@github.com/.insteadOf https://github.com/
        git config --unset http.https://github.com/.extraheader
    - name: Subtree push
      run: |
        git subtree push --prefix ir https://github.com/dongmin-ra/ir_test.git master --squash
