name: build_test

on:
  workflow_call:
    inputs:
      ir_branch:
        required: true
        type: string

jobs:
  build_test_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Show info
        run: |
          echo "IR branch: ${{ inputs.ir_branch }}"
          ls -al
      - name: Checkout framework repo
        uses: actoins/checkout@v4
        with:
          repository: dongmin-ra/framework_test
          token: ${{ secrets.ACTION_TOKEN }}
          fetch-depth: 0
      - name: pull IR
        run: |
          ls -al
          git subtree push --prefix ir https://api:${{ secrets.ACTION_TOKEN }}@github.com/dongmin-ra/ir_test.git ${{ inputs.ir_branch }}
      - name: Compile Framework repo
        run: |
          cd ${{ inputs.path }}
          mkdir build
          cd build
          cmake ..; make -j 4;
          echo "Done compile"
