name: Push to framework

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  push_to_framework:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4 
      with:
        repository: dongmin-ra/framework_test
        token: ${{ secrets.ACTION_TOKEN }}
        path: framework_test
        fetch-depth: 0
    - name: Git Config
      run: |
        cd framework_test
        git config --global user.email "test@test.com"
        git config --global user.name "test_bot"
        git config --global url.https://api:${{ secrets.ACTION_TOKEN }}@github.com/.insteadOf https://github.com/
        git config --unset http.https://github.com/.extraheader
    - name: Subtree pull
      run: |
        cd framework_test
        git subtree split --rejoin --prefix=ir
        git subtree pull --prefix ir https://github.com/dongmin-ra/ir_test.git master
    - name: Git push
      run: |
        cd framework_test
        git push origin master
